In [2]:
import pandas as pd
d={'name':['b','m'],
   'scores':[70,85]}
df2=pd.DataFrame(d)
df2
d1={'name':['ram','shyam','jodu'],
   'scores':[78,85,66]}
df1=pd.DataFrame(d1)

In [3]:
t=pd.concat([df1,df2],ignore_index=True) 
#concatinates two dataframes where both have same column
#ingore index makes it all a continuous index instead of 0 1 2 and 0 1 after that 
t

    name  scores
0    ram      78
1  shyam      85
2   jodu      66
3      b      70
4      m      85

In [4]:
df3=pd.DataFrame({'age':[23,30,22,30,32]})
df3

   age
0   23
1   30
2   22
3   30
4   32

In [15]:
pd.concat([t,df3],axis=1) #not joining, its merging
#for any black/non existent variable we'll 
t

    name  scores  age  age
0    ram      78   23   23
1  shyam      85   30   30
2   jodu      66   22   22
3      b      70   30   30
4      m      85   32   32

In [14]:
t.replace(30,31)

    name  scores  age  age
0    ram      78   23   23
1  shyam      85   31   31
2   jodu      66   22   22
3      b      70   31   31
4      m      85   32   32

In [12]:
t['age'].replace(31,32)

   age  age
0   23   23
1   30   30
2   22   22
3   30   30
4   32   32

In [16]:
t['age'].replace([20,22],[25,23])

   age  age
0   23   23
1   30   30
2   23   23
3   30   30
4   32   32