In [3]:
import pandas as pd
import numpy as np

In [5]:
pd.__version__

'2.2.3'

In [9]:
fruits=['apple','orange','banana','papaya']
pd.Series(fruits)

0     apple
1    orange
2    banana
3    papaya
dtype: object

In [11]:
n=[1,2,3,4,5]
pd.Series(n)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
l=[]
for i in range(10,20,2):
    l.append(i)
pd.Series(a)

0    10
1    12
2    14
3    16
4    18
dtype: int32

In [21]:
marks=[12,23,34,45]
subjects=['phy','chem','math','comp']
pd.Series(marks,index=subjects,name='marks of ram',dtype=float)

phy     12.0
chem    23.0
math    34.0
comp    45.0
Name: marks of ram, dtype: float64

In [23]:
scalar=pd.Series(2,index=[1,2,3,4,5])
print(scalar)

1    2
2    2
3    2
4    2
5    2
dtype: int64

In [35]:
marks={'maths':67,
       'english':78,
       'bengali':89
      }
mas=pd.Series(marks,name="ram's marks")
mas

maths      67
english    78
bengali    89
Name: ram's marks, dtype: int64

In [57]:
mas.size #3
mas.dtype #dtype('int64')
mas.name #"ram's marks"
mas.is_unique #True
mas.values #array([67, 78, 89], dtype=int64)
mas.index #Index(['maths', 'english', 'bengali'], dtype='object')

Index(['maths', 'english', 'bengali'], dtype='object')

In [2]:
import pandas as pd
subs=pd.read_csv('internet.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [17]:
import pandas as pd
bw=pd.read_csv('bollywood.csv')
bw.value_counts()

movie                    lead
Gabbar Is Back           Akshay Kumar       2
Andaaz                   Akshay Kumar       2
Tanu Weds Manu: Returns  Kangana Ranaut     2
Yuvvraaj                 Salman Khan        1
Yuva                     Ajay Devgn         1
                                           ..
Yeh Mera India           Anupam Kher        1
Yeh Saali Aashiqui       Vardhan Puri       1
Youngistaan              Jackky Bhagnani    1
Yun Hota Toh Kya Hota    Paresh Rawal       1
Yakeen (2005 film)       Arjun Rampal       1
Name: count, Length: 1497, dtype: int64

In [20]:
import pandas as pd
ipl=pd.read_csv('kohli_ipl.csv',index_col='match_no')
ipl

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [21]:
ipl.head()

          runs
match_no
1            1
2           23
3           13
4           12
5            1

In [22]:
ipl.tail()

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [23]:
ipl.sample(5)

          runs
match_no
25           7
137         55
2           23
163          8
35           3

In [19]:
import pandas as pd
bw=pd.read_csv('bollywood.csv')
bw.value_counts('lead')

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Zara Sheikh          1
Zareen Khan          1
Ganesh Acharya       1
Garima Agarwal       1
Aanchal Dwivedi      1
Name: count, Length: 566, dtype: int64

In [30]:
ipl.sort_values('match_no',ascending=False).head(1).values[0]
ipl.sort_values('match_no',inplace=True)
ipl

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [45]:
import pandas as pd
l=[1,2,3,4,5,6,7,8,9,10]
sl=pd.Series(l)
print(sl)
sl.sum() #np.int64(55)
print(sl.count()) #10
print(sl.median()) #5.5

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
10
5.5

In [47]:
bw.describe()

                 movie          lead
count             1500          1500
unique            1497           566
top     Gabbar Is Back  Akshay Kumar
freq                 2            48

In [49]:
subs.describe()

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

In [52]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([9,8,7,6,5])
s3=s1+s2
s3
a=s1+4*s2
a
s1.add(s2)

0    10
1    10
2    10
3    10
4    10
dtype: int64